
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview3;

	private global::Gtk.VBox vbox10;

	private global::Gtk.Label label20;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView textview2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button button1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox3;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.VBox vbox5;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label6;

	private global::Gtk.Entry firstNameEntry;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label7;

	private global::Gtk.Entry lastNameEntry;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label8;

	private global::Gtk.Entry emailEntry;

	private global::Gtk.Label label5;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label9;

	private global::Gtk.ComboBox DateCb;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label10;

	private global::Gtk.ComboBox TimeCb;

	private global::Gtk.ComboBox timeMinCb;

	private global::Gtk.Label label19;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label11;

	private global::Gtk.ComboBoxEntry courseCbEntry;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Label label12;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView purposeTv;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label13;

	private global::Gtk.Entry otherEntry;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button button2;

	private global::Gtk.VSeparator vseparator2;

	private global::Gtk.Label label4;

	private global::Gtk.VBox vbox9;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Label label15;

	private global::Gtk.Entry timeZoneEntry;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Label label16;

	private global::Gtk.Entry timeOffsetEntry;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Label label17;

	private global::Gtk.Entry ProfEntry;

	private global::Gtk.HBox hbox17;

	private global::Gtk.Label label18;

	private global::Gtk.Entry entry10;

	private global::Gtk.Label label14;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1920;
		this.DefaultHeight = 1080;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.WidthRequest = 1920;
		this.vbox1.HeightRequest = 700;
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 930;
		this.hpaned1.BorderWidth = ((uint)(1));
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.WidthRequest = 500;
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Today: ");
		this.label1.Justify = ((global::Gtk.Justification)(2));
		this.vbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView();
		this.textview3.WidthRequest = 100;
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow1.Add(this.textview3);
		this.vbox2.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
		w3.Position = 1;
		this.hpaned1.Add(this.vbox2);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox2]));
		w4.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Tomorrow: ");
		this.vbox10.Add(this.label20);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label20]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView();
		this.textview2.WidthRequest = 100;
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.GtkScrolledWindow3.Add(this.textview2);
		this.vbox10.Add(this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.GtkScrolledWindow3]));
		w7.Position = 1;
		this.hpaned1.Add(this.vbox10);
		this.hbox4.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hpaned1]));
		w9.Position = 0;
		this.vbox4.Add(this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
		w10.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 300;
		this.button1.HeightRequest = 100;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Create Event");
		this.hbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox4.Add(this.hbox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.vbox4.Add(this.hbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
		w13.Position = 2;
		this.notebook1.Add(this.vbox4);
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Calendar View");
		this.notebook1.SetTabLabel(this.vbox4, this.label3);
		this.label3.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox3.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator1]));
		w15.Position = 0;
		w15.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("*First Name: ");
		this.hbox5.Add(this.label6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.firstNameEntry = new global::Gtk.Entry();
		this.firstNameEntry.CanFocus = true;
		this.firstNameEntry.Name = "firstNameEntry";
		this.firstNameEntry.IsEditable = true;
		this.firstNameEntry.InvisibleChar = '●';
		this.hbox5.Add(this.firstNameEntry);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.firstNameEntry]));
		w17.Position = 1;
		this.vbox6.Add(this.hbox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("*Last Name: ");
		this.hbox6.Add(this.label7);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label7]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lastNameEntry = new global::Gtk.Entry();
		this.lastNameEntry.CanFocus = true;
		this.lastNameEntry.Name = "lastNameEntry";
		this.lastNameEntry.IsEditable = true;
		this.lastNameEntry.InvisibleChar = '●';
		this.hbox6.Add(this.lastNameEntry);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lastNameEntry]));
		w20.Position = 1;
		this.vbox6.Add(this.hbox6);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("*Email: ");
		this.hbox7.Add(this.label8);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label8]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.emailEntry = new global::Gtk.Entry();
		this.emailEntry.CanFocus = true;
		this.emailEntry.Name = "emailEntry";
		this.emailEntry.IsEditable = true;
		this.emailEntry.InvisibleChar = '●';
		this.hbox7.Add(this.emailEntry);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.emailEntry]));
		w23.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("@eagles.usi.edu");
		this.hbox7.Add(this.label5);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label5]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox6.Add(this.hbox7);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox7]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox5.Add(this.vbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("*Date: ");
		this.hbox8.Add(this.label9);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label9]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.DateCb = global::Gtk.ComboBox.NewText();
		this.DateCb.Name = "DateCb";
		this.hbox8.Add(this.DateCb);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.DateCb]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox7.Add(this.hbox8);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox8]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("*Time: ");
		this.hbox9.Add(this.label10);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label10]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.TimeCb = global::Gtk.ComboBox.NewText();
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("08"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("09"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("10"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("11"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("12"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("01"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("02"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("03"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("04"));
		this.TimeCb.AppendText(global::Mono.Unix.Catalog.GetString("05"));
		this.TimeCb.Name = "TimeCb";
		this.hbox9.Add(this.TimeCb);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.TimeCb]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.timeMinCb = global::Gtk.ComboBox.NewText();
		this.timeMinCb.AppendText(global::Mono.Unix.Catalog.GetString(":00"));
		this.timeMinCb.AppendText(global::Mono.Unix.Catalog.GetString(":15"));
		this.timeMinCb.AppendText(global::Mono.Unix.Catalog.GetString(":30"));
		this.timeMinCb.AppendText(global::Mono.Unix.Catalog.GetString(":45"));
		this.timeMinCb.Name = "timeMinCb";
		this.hbox9.Add(this.timeMinCb);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.timeMinCb]));
		w32.PackType = ((global::Gtk.PackType)(1));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("+");
		this.hbox9.Add(this.label19);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label19]));
		w33.PackType = ((global::Gtk.PackType)(1));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox7.Add(this.hbox9);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("*Course:");
		this.hbox10.Add(this.label11);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label11]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.courseCbEntry = global::Gtk.ComboBoxEntry.NewText();
		this.courseCbEntry.Name = "courseCbEntry";
		this.hbox10.Add(this.courseCbEntry);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.courseCbEntry]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox7.Add(this.hbox10);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox10]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox5.Add(this.vbox7);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox7]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("*Purpose:");
		this.hbox11.Add(this.label12);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label12]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.purposeTv = new global::Gtk.TextView();
		this.purposeTv.CanFocus = true;
		this.purposeTv.Name = "purposeTv";
		this.GtkScrolledWindow2.Add(this.purposeTv);
		this.hbox11.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.GtkScrolledWindow2]));
		w41.Position = 1;
		this.vbox8.Add(this.hbox11);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox11]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Other commits:");
		this.hbox12.Add(this.label13);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label13]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.otherEntry = new global::Gtk.Entry();
		this.otherEntry.CanFocus = true;
		this.otherEntry.Name = "otherEntry";
		this.otherEntry.IsEditable = true;
		this.otherEntry.InvisibleChar = '●';
		this.hbox12.Add(this.otherEntry);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.otherEntry]));
		w44.Position = 1;
		this.vbox8.Add(this.hbox12);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox12]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Submit Request");
		this.hbox13.Add(this.button2);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button2]));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		this.vbox8.Add(this.hbox13);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox13]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.vbox5.Add(this.vbox8);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox8]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		this.hbox3.Add(this.vbox5);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox5]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator();
		this.vseparator2.Name = "vseparator2";
		this.hbox3.Add(this.vseparator2);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator2]));
		w50.Position = 2;
		w50.Fill = false;
		this.notebook1.Add(this.hbox3);
		global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox3]));
		w51.Position = 1;
		// Notebook tab
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Event");
		this.notebook1.SetTabLabel(this.hbox3, this.label4);
		this.label4.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Time Zone:");
		this.hbox14.Add(this.label15);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label15]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.timeZoneEntry = new global::Gtk.Entry();
		this.timeZoneEntry.CanFocus = true;
		this.timeZoneEntry.Name = "timeZoneEntry";
		this.timeZoneEntry.Text = global::Mono.Unix.Catalog.GetString("America/Chicago");
		this.timeZoneEntry.IsEditable = true;
		this.timeZoneEntry.InvisibleChar = '●';
		this.hbox14.Add(this.timeZoneEntry);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.timeZoneEntry]));
		w53.Position = 1;
		this.vbox9.Add(this.hbox14);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox14]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Time Offset:");
		this.hbox15.Add(this.label16);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label16]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.timeOffsetEntry = new global::Gtk.Entry();
		this.timeOffsetEntry.CanFocus = true;
		this.timeOffsetEntry.Name = "timeOffsetEntry";
		this.timeOffsetEntry.Text = global::Mono.Unix.Catalog.GetString("-5:00");
		this.timeOffsetEntry.IsEditable = true;
		this.timeOffsetEntry.InvisibleChar = '●';
		this.hbox15.Add(this.timeOffsetEntry);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.timeOffsetEntry]));
		w56.Position = 1;
		this.vbox9.Add(this.hbox15);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox15]));
		w57.Position = 1;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Professor\'s Email: ");
		this.hbox16.Add(this.label17);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label17]));
		w58.Position = 0;
		w58.Expand = false;
		w58.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.ProfEntry = new global::Gtk.Entry();
		this.ProfEntry.CanFocus = true;
		this.ProfEntry.Name = "ProfEntry";
		this.ProfEntry.Text = global::Mono.Unix.Catalog.GetString("johncarterrr10@gmail.com");
		this.ProfEntry.IsEditable = true;
		this.ProfEntry.InvisibleChar = '●';
		this.hbox16.Add(this.ProfEntry);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.ProfEntry]));
		w59.Position = 1;
		this.vbox9.Add(this.hbox16);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox16]));
		w60.Position = 2;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("label16");
		this.hbox17.Add(this.label18);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label18]));
		w61.Position = 0;
		w61.Expand = false;
		w61.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.entry10 = new global::Gtk.Entry();
		this.entry10.CanFocus = true;
		this.entry10.Name = "entry10";
		this.entry10.IsEditable = true;
		this.entry10.InvisibleChar = '●';
		this.hbox17.Add(this.entry10);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.entry10]));
		w62.Position = 1;
		this.vbox9.Add(this.hbox17);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox17]));
		w63.Position = 3;
		w63.Expand = false;
		w63.Fill = false;
		this.notebook1.Add(this.vbox9);
		global::Gtk.Notebook.NotebookChild w64 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox9]));
		w64.Position = 2;
		// Notebook tab
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Settings");
		this.notebook1.SetTabLabel(this.vbox9, this.label14);
		this.label14.ShowAll();
		this.vbox1.Add(this.notebook1);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
		w65.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("MessageBox");
		this.vbox3.Add(this.label2);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
		w66.Position = 0;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.WidthRequest = 1900;
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add(this.textview1);
		this.vbox3.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
		w68.Position = 1;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w69.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.createEventBt);
		this.button2.Clicked += new global::System.EventHandler(this.submitBt);
	}
}
